# Generated by Django 4.1.7 on 2023-04-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
