# Generated by Django 4.1.7 on 2023-05-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(blank=True, max_length=200, null=True)),
                ('public_key', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
